travis:
  secure:
    BINSTAR_TOKEN: IW/9niLmAxTOYfAEaY3RZUyX3q8BTAXdBj0UwM/9eCJtVQHQhHFECleBj0ZJWbBTxqheP/9XEpLqGJTw4EyDb4bTj6LNE7fxwG8Nr0vdvraPdkwBQuojn6c5hGBh3ReXnSCMYoQDHUM9Bu+vV+in8R0gk+d565zXDOUDuHe9+UImkc/7Iqq5lPdupXacXwue9Bi1p7iF9GkbqxoShqb+4xemQBkDCrjf3Jf4R0GvNWljlc+DIhfPRbaEOUy8yRQbAol+9GYW+LL5y1hVznBRQXg/z55iFNhOd98T9afAvKoJQNZGIxyl4xV40WVy3+VEYjE/rTk7KTCTi+ofrOAF3o0QhDZ9eh68vy7Mcbs2TXwyEwTDJEadTBswBz0TdZN+oiJ6oEVa0JL8CFErdK5Ic63EN1rEe8ogR3l4wH8Fx1jB07ShvLwKUR3SGmcw1Ms/DRF8SROuuRznsQTUnt+ZmSxS3EPkMycXTwqsNFT1U2RKcDNcFX3Hgrg8YD0P4rIfjdYWlgyXNOnF7naac4YBn3ZYZTDIxFD6CzFl01J8Pp3wKMJmybKbi5lZOofZWI15uhHEA+1eB184eWUojt96lFOV7RTdiXJQKmZfaOYs4cFjLLTVsVYyS1AddinW6Jbm0hex8MVs/XLH0cIsqn8vXpGacoSYfTzSLjwqGi1fIEM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
